name: "SunSync"
description: "Home Assistant add-on for syncing solar/inverter data from SunSynk.net"
version: "1.0.15"
slug: "sunsync"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true

options:
  sunsynk_user: ""
  sunsynk_pass: ""
  sunsynk_serial: ""
  Home_Assistant_IP: ""
  Home_Assistant_PORT: 8123
  HA_LongLiveToken: ""
  Refresh_rate: 300
  Enable_HTTPS: false
  Enable_Verbose_Log: false
  Entity_Prefix: "sunsync"
  Include_Serial_In_Name: true

schema:
  sunsynk_user: str
  sunsynk_pass: password
  sunsynk_serial: str
  Home_Assistant_IP: str
  Home_Assistant_PORT: int
  HA_LongLiveToken: password
  Refresh_rate: int
  Enable_HTTPS: bool
  Enable_Verbose_Log: bool
  Entity_Prefix: str
  Include_Serial_In_Name: bool
