name: "SunSync"
description: "Home Assistant add-on for syncing solar/inverter data from SynSynk.net"
version: "1.0.13"
slug: "sunsync"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true

options:
  sunsynk_user: ""
  sunsynk_pass: ""
  sunsynk_serial: ""
  Home_Assistant_IP: ""
  Home_Assistant_PORT: 8123
  HA_LongLiveToken: ""
  Refresh_rate: 300
  Enable_HTTPS: false
  Enable_Verbose_Log: false
  entity_prefix: "sunsync"
  include_serial_in_name: true

schema:
  sunsynk_user: str
  sunsynk_pass: password
  sunsynk_serial: str
  Home_Assistant_IP: str
  Home_Assistant_PORT: int
  HA_LongLiveToken: password
  Refresh_rate: int
  Enable_HTTPS: bool
  Enable_Verbose_Log: bool
  entity_prefix:
    name: Entity Prefix
    description: Prefix used for all entities (e.g., sensor.prefix_battery_soc)
    default: "sunsync"
  include_serial_in_name:
    name: Include Serial Number
    description: Include inverter serial number in entity names
    default: true
